import type { DealOpportunity, BuyingSignal, CompetitorProfile, RevenueForecast } from '../../types';

export const DEMO_OPPORTUNITIES: DealOpportunity[] = [
  {
    id: 'opp-001',
    builderName: 'VTP Group',
    projectName: 'VTP Luxuria Baner',
    projectType: 'luxury_residential',
    location: 'Baner',
    city: 'Pune',
    estimatedValue: 12500000,
    confidenceScore: 94,
    confidenceFactors: [
      { label: 'Budget Match', score: 95, weight: 'high', description: 'Budget aligns perfectly with premium inventory' },
      { label: 'Urgency', score: 90, weight: 'high', description: 'Immediate purchase intent detected' },
      { label: 'Engagement', score: 88, weight: 'medium', description: 'Multiple property brochure downloads' },
      { label: 'Location Fit', score: 92, weight: 'medium', description: 'Preferred area matches available projects' },
      { label: 'Financial Health', score: 85, weight: 'low', description: 'Pre-approved for loan amount' },
    ],
    dealStage: 'closing',
    expectedCommission: calculateCommission(12500000),
    reasons: [
      'Premium budget (₹1.25 Cr) aligns perfectly with luxury inventory in Baner',
      'High urgency — requested site visit within this week',
      'Complete contact information provided with verified phone',
      'Previously purchased from partner builder — high trust signal',
    ],
    recommendedActions: [
      '📞 Schedule closing call within 24 hours',
      '🏗️ Offer exclusive penthouse viewing this weekend',
      '📄 Prepare final offer letter with 3% commission breakdown',
      '💎 Share premium project portfolio with financing options',
    ],
    signals: [
      { id: 'sig-001', type: 'rera_filing', title: 'RERA Filing Received', description: 'VTP Group filed RERA for Baner project with 124 units', source: 'Maharera', date: '2026-07-15', relevanceScore: 95, impact: 'high' },
      { id: 'sig-002', type: 'government_approval', title: 'Environmental Clearance Approved', description: 'MoEF granted environmental clearance for Phase 2', source: 'MoEF', date: '2026-07-10', relevanceScore: 88, impact: 'high' },
      { id: 'sig-003', type: 'construction_start', title: 'Construction Started — Phase 2', description: 'Site preparation commenced for 45 luxury apartments', source: 'PMC', date: '2026-07-05', relevanceScore: 82, impact: 'medium' },
    ],
    createdAt: '2026-07-18T10:30:00Z',
    updatedAt: '2026-07-20T14:00:00Z',
  },
  {
    id: 'opp-002',
    builderName: 'Godrej Properties',
    projectName: 'Godrej Woodlands Kharadi',
    projectType: 'luxury_residential',
    location: 'Kharadi',
    city: 'Pune',
    estimatedValue: 8200000,
    confidenceScore: 81,
    confidenceFactors: [
      { label: 'Budget Match', score: 75, weight: 'high', description: 'Budget suitable for 2BHK premium' },
      { label: 'Urgency', score: 70, weight: 'high', description: 'Planning purchase within 2 months' },
      { label: 'Engagement', score: 85, weight: 'medium', description: 'Active WhatsApp conversation' },
      { label: 'Location Fit', score: 80, weight: 'medium', description: 'Kharadi is growing IT hub' },
    ],
    dealStage: 'qualifying',
    expectedCommission: calculateCommission(8200000),
    reasons: [
      'Godrej Properties has strong brand trust and credibility',
      'Active WhatsApp engagement — responded within 5 minutes',
      'Kharadi location is a booming IT corridor with high appreciation',
      'Family expansion suggests need for larger home',
    ],
    recommendedActions: [
      '📱 Send property brochure and pricing via WhatsApp',
      '📅 Suggest weekend site visit with financing calculator',
      '📧 Share Godrej project portfolio and past success stories',
      '🏷️ Offer early-bird discount for Phase 2 bookings',
    ],
    signals: [
      { id: 'sig-004', type: 'project_launch', title: 'Godrej Woodlands Phase 2 Launch', description: 'New 2BHK and 3BHK towers announced in Kharadi', source: 'Godrej Properties', date: '2026-07-12', relevanceScore: 90, impact: 'high' },
      { id: 'sig-005', type: 'market_trend', title: 'Kharadi Property Prices Up 12%', description: 'Quarterly appreciation in Kharadi micro-market', source: 'SquareYards', date: '2026-07-08', relevanceScore: 75, impact: 'medium' },
    ],
    createdAt: '2026-07-16T08:00:00Z',
    updatedAt: '2026-07-19T11:00:00Z',
  },
  {
    id: 'opp-003',
    builderName: 'Amit Shah',
    projectName: 'Balewadi Heights',
    projectType: 'luxury_residential',
    location: 'Balewadi',
    city: 'Pune',
    estimatedValue: 21000000,
    confidenceScore: 96,
    confidenceFactors: [
      { label: 'Budget Match', score: 98, weight: 'high', description: 'Premium budget — luxury segment' },
      { label: 'Urgency', score: 95, weight: 'high', description: 'Requires possession within 3 months' },
      { label: 'Engagement', score: 92, weight: 'medium', description: 'Multiple site visits completed' },
      { label: 'Financial Health', score: 90, weight: 'low', description: 'Cash purchase — no financing required' },
    ],
    dealStage: 'negotiation',
    expectedCommission: calculateCommission(21000000),
    reasons: [
      'Ultra-premium budget (₹2.1 Cr) — highest value opportunity in pipeline',
      'Cash buyer with no financing contingency — faster close',
      'Multiple site visits indicate serious intent',
      'Requesting customization options — emotionally invested',
    ],
    recommendedActions: [
      '💎 Arrange meeting with architect for customization discussion',
      '📄 Prepare detailed cost breakdown with 3% commission clause',
      '🏗️ Offer exclusive rooftop garden access as closing incentive',
      '🤝 Introduce to interior design partner for value-add',
    ],
    signals: [
      { id: 'sig-006', type: 'funding_raised', title: 'Amit Shah Ventures — ₹50 Cr Fundraise', description: 'Sold technology venture, investing in real estate', source: 'Economic Times', date: '2026-07-14', relevanceScore: 98, impact: 'high' },
      { id: 'sig-007', type: 'news_coverage', title: 'Featured in Pune Builder Directory', description: 'Listed as top potential buyer for luxury properties', source: 'Times Property', date: '2026-07-01', relevanceScore: 85, impact: 'medium' },
    ],
    createdAt: '2026-07-14T16:00:00Z',
    updatedAt: '2026-07-20T09:00:00Z',
  },
  {
    id: 'opp-004',
    builderName: 'Kolte Patil',
    projectName: 'Kolte Patila Aurora Wakad',
    projectType: 'luxury_residential',
    location: 'Wakad',
    city: 'Pune',
    estimatedValue: 9500000,
    confidenceScore: 78,
    confidenceFactors: [
      { label: 'Budget Match', score: 80, weight: 'high', description: 'Budget aligns with 3BHK category' },
      { label: 'Urgency', score: 65, weight: 'high', description: 'Planning within next quarter' },
      { label: 'Engagement', score: 75, weight: 'medium', description: 'Site visit scheduled' },
    ],
    dealStage: 'proposal',
    expectedCommission: calculateCommission(9500000),
    reasons: [
      'Site visit already scheduled — high intent signal',
      'Kolte Patil brand has strong reputation in Pune',
      'Wakad location benefits from proximity to IT parks',
      'Family of 4 looking for 3BHK — genuine requirement',
    ],
    recommendedActions: [
      '📅 Confirm site visit with personalized itinerary',
      '📄 Prepare comparison of available 3BHK units with pricing',
      '🏦 Share home loan pre-approval partner contacts',
      '🎁 Offer special launch festival discount',
    ],
    signals: [
      { id: 'sig-008', type: 'permit_issued', title: 'Kolte Patila Aurora Occupancy Certificate', description: 'OC received for Tower A and B', source: 'PMC', date: '2026-07-11', relevanceScore: 85, impact: 'high' },
    ],
    createdAt: '2026-07-15T12:00:00Z',
    updatedAt: '2026-07-19T16:00:00Z',
  },
  {
    id: 'opp-005',
    builderName: 'Vikram Patil Constructions',
    projectName: 'Patil Elite Hinjewadi',
    projectType: 'luxury_residential',
    location: 'Hinjewadi',
    city: 'Pune',
    estimatedValue: 17500000,
    confidenceScore: 99,
    confidenceFactors: [
      { label: 'Budget Match', score: 100, weight: 'high', description: 'Deal closed — full budget utilized' },
      { label: 'Urgency', score: 100, weight: 'high', description: 'Completed purchase' },
      { label: 'Satisfaction', score: 98, weight: 'medium', description: 'Positive feedback and referral potential' },
    ],
    dealStage: 'closed_won',
    expectedCommission: calculateCommission(17500000),
    reasons: [
      '✅ Deal successfully closed — full payment received',
      '💰 Commission of ₹5.25 L realized',
      '⭐ Client expressed high satisfaction — referral potential',
      '🏗️ Exploring second property for investment',
    ],
    recommendedActions: [
      '🎉 Send thank-you note with closing gift',
      '📱 Request Google review and testimonial',
      '🤝 Ask for referrals in builder network',
      '📧 Follow up in 3 months for investment property needs',
    ],
    signals: [
      { id: 'sig-009', type: 'news_coverage', title: 'Vikram Patil Featured in Builders Magazine', description: 'Recognized as top emerging real estate developer', source: 'Builders India', date: '2026-07-02', relevanceScore: 80, impact: 'medium' },
    ],
    createdAt: '2026-07-10T09:00:00Z',
    updatedAt: '2026-07-18T17:00:00Z',
  },
];

export const DEMO_SIGNALS: BuyingSignal[] = [
  { id: 'sig-001', type: 'rera_filing', title: 'RERA Filing Received', description: 'VTP Group filed RERA for Baner project with 124 units. This indicates project legitimacy and regulatory compliance.', source: 'Maharera', date: '2026-07-15', relevanceScore: 95, impact: 'high' },
  { id: 'sig-002', type: 'government_approval', title: 'Environmental Clearance Approved', description: 'MoEF granted environmental clearance for Phase 2 of Balewadi development.', source: 'MoEF', date: '2026-07-10', relevanceScore: 88, impact: 'high' },
  { id: 'sig-003', type: 'builder_hiring', title: 'VTP Group Hiring 45 Sales Professionals', description: 'Massive hiring drive indicates new project launches and expansion.', source: 'Naukri.com', date: '2026-07-08', relevanceScore: 92, impact: 'high' },
  { id: 'sig-004', type: 'land_acquisition', title: 'Godrej Acquires 5 Acres in Kharadi', description: 'Land acquisition for upcoming luxury residential project.', source: 'Property Registration', date: '2026-07-05', relevanceScore: 85, impact: 'high' },
  { id: 'sig-005', type: 'funding_raised', title: 'Amit Shah Ventures — ₹50 Cr Fundraise', description: 'Sold technology venture, now actively investing in premium real estate.', source: 'Economic Times', date: '2026-07-14', relevanceScore: 98, impact: 'high' },
  { id: 'sig-006', type: 'project_launch', title: 'Godrej Woodlands Phase 2 Launch', description: 'New 2BHK and 3BHK towers announced in Kharadi with modern amenities.', source: 'Godrej Properties', date: '2026-07-12', relevanceScore: 90, impact: 'high' },
  { id: 'sig-007', type: 'market_trend', title: 'Pune West Property Prices Up 18% YoY', description: 'Baner, Balewadi, Wakad corridor seeing highest appreciation in Pune.', source: 'SquareYards Report', date: '2026-07-11', relevanceScore: 82, impact: 'medium' },
  { id: 'sig-008', type: 'construction_start', title: 'Construction Started — Phase 2', description: 'Site preparation commenced for 45 luxury apartments in Wakad.', source: 'PMC', date: '2026-07-05', relevanceScore: 80, impact: 'medium' },
  { id: 'sig-009', type: 'partnership', title: 'Kolte Patil Partners with IKEA', description: 'Strategic partnership for fully-furnished apartment packages.', source: 'Business Standard', date: '2026-07-03', relevanceScore: 75, impact: 'medium' },
  { id: 'sig-010', type: 'expansion', title: 'VTP Group Expanding to Hyderabad Market', description: 'Forays into Hyderabad with 3 new projects in financial district.', source: 'Telangana Today', date: '2026-07-01', relevanceScore: 72, impact: 'medium' },
  { id: 'sig-011', type: 'permit_issued', title: 'Kolte Patila Aurora Occupancy Certificate', description: 'OC received for Tower A and B — ready for possession.', source: 'PMC', date: '2026-07-11', relevanceScore: 85, impact: 'high' },
  { id: 'sig-012', type: 'news_coverage', title: 'Vikram Patil Featured in Builders Magazine', description: 'Recognized as top emerging real estate developer in Pune.', source: 'Builders India', date: '2026-07-02', relevanceScore: 78, impact: 'low' },
];

export const DEMO_COMPETITORS: CompetitorProfile[] = [
  {
    id: 'comp-001',
    name: 'Lodha Group',
    logo: '🏗️',
    headquarters: 'Mumbai, Maharashtra',
    foundedYear: 1995,
    projects: [
      { name: 'Lodha Palava', location: 'Dombivli', type: 'Township', status: 'ongoing', totalValue: 5000000000, units: 25000, launchedDate: '2010' },
      { name: 'Lodha World Towers', location: 'Lower Parel', type: 'Luxury', status: 'ongoing', totalValue: 3000000000, units: 1500, launchedDate: '2018' },
    ],
    annualRevenue: '₹3,200 Cr',
    growthRate: 22,
    marketShare: 8,
    totalProjects: 42,
    activeProjects: 18,
    totalUnitsDelivered: 35000,
    pricing: 'luxury',
    strengths: ['Strong brand recognition nationwide', 'Superior construction quality', 'Massive land bank in MMR', 'Excellent financial management'],
    weaknesses: ['Premium pricing limits market', 'Delayed deliveries in some projects', 'Limited presence in Pune'],
    recentActivity: ['Launched Luxury Collection in Thane', 'Raised ₹500 Cr through NCDs', 'Expanded to Goa market'],
    hiringTrend: 'increasing',
    hiringCount: 120,
    fundingInfo: 'Listed on BSE/NSE — Market Cap ₹15,000 Cr',
    expansionPlans: ['Entering Pune market with 500-acre township', 'Launching co-living brand', 'Developing data center parks'],
    createdAt: '2026-07-15T00:00:00Z',
  },
  {
    id: 'comp-002',
    name: 'Prestige Group',
    logo: '🏛️',
    headquarters: 'Bengaluru, Karnataka',
    foundedYear: 1986,
    projects: [
      { name: 'Prestige City', location: 'Bengaluru', type: 'Township', status: 'ongoing', totalValue: 2000000000, units: 5000, launchedDate: '2015' },
    ],
    annualRevenue: '₹2,800 Cr',
    growthRate: 18,
    marketShare: 6,
    totalProjects: 85,
    activeProjects: 25,
    totalUnitsDelivered: 40000,
    pricing: 'premium',
    strengths: ['Massive unit delivery track record', 'Strong South India presence', 'Diverse portfolio across segments'],
    weaknesses: ['Limited presence in North India', 'Some projects facing cash flow issues'],
    recentActivity: ['Entered luxury hotel segment', 'Launched 3 new projects in Bengaluru', 'Partnership with Marriott'],
    hiringTrend: 'stable',
    hiringCount: 45,
    fundingInfo: 'Blackstone joint venture for commercial assets',
    expansionPlans: ['Expanding to Pune and Hyderabad', 'Developing 2 million sq ft office space'],
    createdAt: '2026-07-14T00:00:00Z',
  },
  {
    id: 'comp-003',
    name: 'Oberoi Realty',
    logo: '👑',
    headquarters: 'Mumbai, Maharashtra',
    foundedYear: 1998,
    projects: [
      { name: 'Oberoi Elysian', location: 'Worli', type: 'Luxury', status: 'ongoing', totalValue: 1500000000, units: 200, launchedDate: '2022' },
    ],
    annualRevenue: '₹1,500 Cr',
    growthRate: 15,
    marketShare: 4,
    totalProjects: 18,
    activeProjects: 8,
    totalUnitsDelivered: 8000,
    pricing: 'luxury',
    strengths: ['Ultra-luxury positioning', 'Superior design and architecture', 'Excellent customer satisfaction'],
    weaknesses: ['Limited project volume', 'Only Mumbai and Pune focus', 'Very premium pricing'],
    recentActivity: ['Launched Oberli Garden in Thane', 'Received approval for Borivali project'],
    hiringTrend: 'stable',
    hiringCount: 25,
    expansionPlans: ['Exploring Chennai market', 'Luxury resort development in Alibaug'],
    createdAt: '2026-07-13T00:00:00Z',
  },
  {
    id: 'comp-004',
    name: 'Kolte Patil Developers',
    logo: '🏘️',
    headquarters: 'Pune, Maharashtra',
    foundedYear: 1982,
    projects: [
      { name: 'Kolte Patila Aurora', location: 'Wakad', type: 'Luxury', status: 'ongoing', totalValue: 500000000, units: 450, launchedDate: '2023' },
    ],
    annualRevenue: '₹800 Cr',
    growthRate: 12,
    marketShare: 5,
    totalProjects: 65,
    activeProjects: 15,
    totalUnitsDelivered: 18000,
    pricing: 'mid_range',
    strengths: ['Strong Pune presence', 'Affordable luxury positioning', 'Good delivery track record'],
    weaknesses: ['Limited national presence', 'Lower margin compared to luxury peers'],
    recentActivity: ['Launched new project in Baner', 'Partnership with IKEA for furniture packages'],
    hiringTrend: 'increasing',
    hiringCount: 35,
    expansionPlans: ['Entering Nashik market', 'Developing plotted development in Hinjewadi'],
    createdAt: '2026-07-12T00:00:00Z',
  },
];

export const DEMO_FORECASTS: RevenueForecast[] = [
  {
    month: 'Jul 2026',
    expectedCommission: 250000,
    probableCommission: 375000,
    optimisticCommission: 525000,
    deals: [
      { name: 'VTP Baner', value: 12500000, probability: 0.94 },
      { name: 'Balewadi Heights', value: 21000000, probability: 0.60 },
    ],
  },
  {
    month: 'Aug 2026',
    expectedCommission: 180000,
    probableCommission: 420000,
    optimisticCommission: 630000,
    deals: [
      { name: 'Kolte Patil Wakad', value: 9500000, probability: 0.78 },
      { name: 'Godrej Kharadi', value: 8200000, probability: 0.55 },
    ],
  },
  {
    month: 'Sep 2026',
    expectedCommission: 150000,
    probableCommission: 280000,
    optimisticCommission: 450000,
    deals: [
      { name: 'Kharadi Phase 2', value: 15000000, probability: 0.30 },
    ],
  },
  {
    month: 'Oct 2026',
    expectedCommission: 120000,
    probableCommission: 200000,
    optimisticCommission: 350000,
    deals: [
      { name: 'Hinjewadi Premium', value: 12000000, probability: 0.25 },
    ],
  },
  {
    month: 'Nov 2026',
    expectedCommission: 100000,
    probableCommission: 180000,
    optimisticCommission: 300000,
    deals: [
      { name: 'Baner Phase 3', value: 10000000, probability: 0.20 },
    ],
  },
  {
    month: 'Dec 2026',
    expectedCommission: 80000,
    probableCommission: 200000,
    optimisticCommission: 400000,
    deals: [
      { name: 'Q4 Closing Deals', value: 20000000, probability: 0.15 },
    ],
  },
];

import { calculateCommission } from '../../types';
